name: xebuonho_rider
description: Xebuonho - Ứng dụng đặt xe cho khách hàng
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  dio: ^5.4.0
  provider: ^6.1.1
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
